spring:
  application:
    name: webflux
  server:
    port: 8080
    servlet:
      context-path: /webflux
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-details: always
          show-components: always
  data:
    #mongodb:
      #uri: mongodb://mongodb/sicredidb
      #uri: mongodb://192.168.15.3:27017/webfluxdb
    mongodb:
    #  authentication-database: admin
      database: webfluxdb
      host: 192.168.15.3
    #  password: root
      port: 27017
    #  username: root