server:
  port: 8088
  
#registra a aplicação no Eureka Server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true #utiliza o ip ao invés de usar o hostname