server:
  port: 8888

#spring:
#  profiles:
#    active: native #indica para o config server onde deve buscar as configurações (native: pega do filesystem na máquina)
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: /ambiente/projetos/github/spring-cloud/spring-cloud-api-configs #lê os arquivos .yml de configuração que estão neste diretório
 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nickborges/spring-cloud
          search-paths: 
            - spring-cloud-api-configs/loja
            - spring-cloud-api-configs/usuario