spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:usuario-dev
    username: sa_dev
    password:
  h2:
    console:
      enabled: true
      path: /h2-console/dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true